/**
 * Backup & Portability — shared constants (docs/adr/0034-backup-and-portability.md).
 *
 * Client-safe (no `server-only`): the format identifiers are also used by
 * the settings UI. Nothing here touches the DB or secrets.
 */

/** `manifest.format` — the magic string that identifies an ASODITECH backup. */
export const BACKUP_FORMAT = "ASODITECH_BACKUP" as const;

/** `manifest.version` — the ASODITECH backup FORMAT version. Bump only on a
 * breaking change to the package layout / model set. A restore refuses a
 * package whose version it does not know. */
export const BACKUP_FORMAT_VERSION = 1 as const;

/** Every format version this build's restore engine can read. */
export const SUPPORTED_BACKUP_FORMAT_VERSIONS: readonly number[] = [1];

/** Container framing (src/lib/backup/container.ts): 6-byte header, then a
 * 12-byte IV, a 16-byte GCM tag, then the ciphertext. */
export const CONTAINER_MAGIC = Buffer.from("ASB1", "ascii"); // 4 bytes
export const CONTAINER_VERSION = 1;
export const CONTAINER_HEADER_LENGTH = 6; // magic(4) + version(1) + reserved(1)
export const CONTAINER_IV_LENGTH = 12;
export const CONTAINER_TAG_LENGTH = 16;

export const BACKUP_FILE_EXTENSION = ".asb";

/**
 * Phase 1 is a synchronous, in-memory export/restore. These caps keep a
 * "normal tenant" well inside a serverless function's time/memory budget;
 * a tenant past them is told to wait for the background-job phase rather
 * than risking a half-applied restore. See the ADR's "Performance".
 */
export const MAX_TOTAL_ROWS = 100_000;
export const MAX_CONTAINER_BYTES = 25 * 1024 * 1024; // 25 MiB sealed

/** How long an unconsumed RESTORE_UPLOAD / a PRE_RESTORE_SNAPSHOT payload
 * is kept before it is eligible for pruning. */
export const RESTORE_UPLOAD_TTL_MS = 60 * 60 * 1000; // 1 h
export const SAFETY_SNAPSHOT_TTL_MS = 7 * 24 * 60 * 60 * 1000; // 7 d

/** Fields deliberately stripped from a backup — surfaced in the manifest so
 * a restore (and an auditor) can see exactly what was and wasn't kept. */
export const SANITIZED_FIELDS: Record<string, readonly string[]> = {
  User: ["passwordHash", "isPlatformAdmin"],
  Integration: ["credentialsEncrypted"],
  ShippingProvider: ["credentialsEncrypted"],
};

/** Tenant-scoped models deliberately NOT exported, with the reason. */
export const EXCLUDED_MODELS: Record<string, string> = {
  Session: "auth tokens — ephemeral, never portable",
  Invitation: "contains a secret token hash — ephemeral provisioning state",
  PasswordResetToken: "contains a secret token hash — ephemeral",
  Notification: "ephemeral in-app UI state, regenerated by events",
  WebhookEvent: "integration replay-protection dedupe log — meaningless after reconnect",
  ShipmentWebhookEvent: "delivery replay-protection dedupe log — meaningless after reconnect",
  SyncRun: "integration sync run history — meaningless after reconnect",
  BackupRun: "the backup module's own bookkeeping — never backs itself up",
};
