// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// `prisma/config`'s `env()` helper throws at config-load time when the
// variable is missing, which breaks `prisma generate` (run from
// `postinstall`) in any environment where the database URL isn't present
// during install — e.g. Vercel resolves project env vars for the build
// step but not always for the preceding `pnpm install`, and plain CI
// installs never have it. `prisma generate` only reads the schema and
// never connects, so it must not require a real URL.
//
// So we read from `process.env` directly (undefined, not a throw, when
// absent) and fall back to a syntactically valid placeholder. Commands
// that actually connect (`migrate deploy`, `db push`, `studio`) run after
// the real env vars are available and use them; `generate` runs with the
// placeholder and succeeds without ever opening a connection. `DIRECT_URL`
// falls back to `DATABASE_URL` for single-connection (unpooled) setups.
const PLACEHOLDER_URL = "postgresql://placeholder:placeholder@localhost:5432/placeholder";
const databaseUrl = process.env.DATABASE_URL ?? PLACEHOLDER_URL;
const directUrl = process.env.DIRECT_URL ?? databaseUrl;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: databaseUrl,
    directUrl,
  },
});
