import type { DocArticle } from "../types";

const LAST_UPDATED = "2026-09-10";

export const bienDemarrerArticles: DocArticle[] = [
  {
    slug: "bien-demarrer/presentation-asoditech",
    title: "Présentation d'ASODITECH",
    category: "bien-demarrer",
    tagline:
      "ASODITECH est le système de gestion e-commerce qui centralise vos commandes, votre stock, votre livraison et votre finance — que vos ventes viennent de WooCommerce, de Shopify ou d'une saisie manuelle.",
    prerequisites: [],
    steps: [],
    body: [
      {
        type: "p",
        text: "ASODITECH relie les modules qu'une boutique e-commerce marocaine utilise déjà séparément : catalogue produits, stock multi-entrepôts, confirmation téléphonique des commandes (courant en vente à la livraison), création d'expéditions chez un transporteur, suivi de livraison, et rentabilité réelle (coût, marge, commission).",
      },
      {
        type: "list",
        items: [
          "Boutique / Intégrations — connecte WooCommerce et/ou Shopify ; les commandes et produits se synchronisent automatiquement.",
          "Produits — catalogue simple ou variable, avec prix de vente et coût d'achat.",
          "Commandes — du statut Nouvelle jusqu'à Livrée, Retour ou Annulée.",
          "Confirmation — la file d'appel partagée pour valider une commande avant expédition.",
          "Stock — entrepôts, mouvements, transferts, inventaires.",
          "Livraison — transporteurs, création d'expédition, suivi, retours.",
          "Finance / Rentabilité — coût, marge et dépenses réels, pas estimés.",
          "Rapports — ventes, rentabilité, stock, livraison, clients, trésorerie.",
          "Utilisateurs & permissions — chaque rôle voit et peut faire exactement ce qui lui est autorisé.",
        ],
      },
      {
        type: "callout",
        tone: "info",
        title: "Chaque entreprise est isolée",
        text: "Vos données (commandes, clients, stock, finance...) appartiennent uniquement à votre compte. Aucun autre client ASODITECH ne peut jamais les voir, et vous ne voyez jamais les leurs.",
      },
    ],
    related: ["bien-demarrer/comment-fonctionne-le-systeme", "bien-demarrer/checklist-de-demarrage"],
    lastUpdated: LAST_UPDATED,
    keywords: ["c'est quoi asoditech", "à quoi sert asoditech", "présentation"],
  },
  {
    slug: "bien-demarrer/comment-fonctionne-le-systeme",
    title: "Comment fonctionne le système",
    category: "bien-demarrer",
    tagline: "Comprendre le fil conducteur : d'où vient une commande, comment elle avance, et ce qui se passe automatiquement.",
    steps: [
      "Une commande arrive — synchronisée depuis WooCommerce/Shopify, ou créée manuellement (téléphone, WhatsApp).",
      "Un agent de confirmation l'appelle et confirme (file « Confirmation ») — le stock est alors réservé.",
      "Une expédition est créée chez un transporteur — le stock réservé devient une sortie réelle.",
      "Le transporteur livre, échoue ou retourne le colis — le statut de la commande et le coût de livraison réel se mettent à jour en conséquence.",
      "Une fois livrée, la commission de l'agent de confirmation est acquise et la rentabilité (coût réel, marge) est calculée.",
    ],
    body: [
      {
        type: "callout",
        tone: "info",
        text: "Rien n'est deviné : le coût d'une commande est celui figé au moment de la vente (« snapshot »), et le coût de livraison est celui réellement facturé par le transporteur — jamais une estimation.",
      },
    ],
    related: ["commandes/comprendre-les-statuts", "confirmation/workflow-de-confirmation", "finance/coup-produit"],
    lastUpdated: LAST_UPDATED,
    keywords: ["fonctionnement général", "cycle de vie d'une commande"],
  },
  {
    slug: "bien-demarrer/premiere-connexion",
    title: "Première connexion",
    category: "bien-demarrer",
    tagline: "Accepter une invitation et se connecter à ASODITECH pour la première fois.",
    prerequisites: ["Avoir reçu un lien d'invitation par e-mail (ou d'un administrateur)."],
    steps: [
      "Ouvrir le lien d'invitation reçu par e-mail.",
      "Choisir un mot de passe.",
      "Valider — le compte est activé et vous êtes connecté.",
    ],
    whatYouShouldSee: "Le tableau de bord de votre entreprise, filtré selon les permissions de votre rôle.",
    commonMistakes: [
      "Attendre trop longtemps pour ouvrir le lien : il expire 7 jours après l'envoi.",
      "Cliquer deux fois sur le même lien après l'avoir déjà utilisé.",
    ],
    troubleshooting: [
      {
        symptom: "Le lien d'invitation affiche « Cette invitation n'est plus valide »",
        cause: "Le lien a expiré (plus de 7 jours), a déjà été utilisé, ou a été révoqué par un administrateur.",
        check: "Vérifiez la date de réception de l'e-mail d'invitation.",
        solution: "Demandez à un administrateur (permission « Utilisateurs ») de renvoyer une nouvelle invitation depuis Utilisateurs.",
        expectedResult: "Un nouvel e-mail d'invitation, valable 7 jours, est reçu.",
        errorStrings: ["Cette invitation n'est plus valide.", "Il a peut-être expiré, déjà été utilisé, ou été révoqué."],
      },
    ],
    related: ["utilisateurs/invitation", "utilisateurs/mot-de-passe"],
    tryNow: { label: "Se connecter", href: "/connexion" },
    lastUpdated: LAST_UPDATED,
    keywords: ["invitation expirée", "premier accès", "activer mon compte"],
  },
  {
    slug: "bien-demarrer/comprendre-le-tableau-de-bord",
    title: "Comprendre le tableau de bord",
    category: "bien-demarrer",
    tagline: "Le tableau de bord résume l'activité de la période choisie : chiffre d'affaires, commandes, livraisons, stock, confirmation et commissions.",
    permission: "dashboard.view",
    prerequisites: [],
    steps: [
      "Choisir la période en haut de la page (aujourd'hui, hier, ce mois, ce trimestre, cette année).",
      "Lire les indicateurs financiers (CA, charges, bénéfice net, panier moyen) — visibles uniquement avec la permission Finance.",
      "Lire les indicateurs opérationnels (commandes, nouveaux clients, taux de livraison réussie, stock faible).",
      "Si vous avez la permission Confirmation, consulter le bloc « À confirmer / Confirmées / À rappeler ».",
      "Si vous avez la permission Commissions, consulter le bloc commission et le lien « Voir la performance confirmation ».",
    ],
    whatYouShouldSee:
      "Un indicateur qui ne peut pas être calculé (par exemple le bénéfice net sans coût d'achat renseigné) affiche « Non calculable » plutôt qu'un chiffre inventé.",
    related: ["finance/rentabilite", "confirmation/workflow-de-confirmation"],
    tryNow: { label: "Ouvrir le tableau de bord", href: "/tableau-de-bord" },
    lastUpdated: LAST_UPDATED,
    keywords: ["dashboard", "indicateurs", "non calculable"],
  },
  {
    slug: "bien-demarrer/configuration-initiale",
    title: "Configuration initiale",
    category: "bien-demarrer",
    tagline: "Les quelques réglages à faire avant votre première commande réelle.",
    permission: "settings.manage",
    prerequisites: ["Rôle OWNER ou ADMIN pour la plupart de ces réglages."],
    steps: [
      "Renseigner les informations de l'entreprise dans Paramètres → Général (nom, coordonnées, logo — utilisés sur les factures et rapports imprimés).",
      "Connecter WooCommerce et/ou Shopify si vous vendez déjà en ligne (voir « Connecter WooCommerce/Shopify »).",
      "Vérifier l'entrepôt par défaut créé automatiquement à la création de votre compte (Catalogue → Emplacements).",
      "Inviter votre équipe avec le rôle adapté à chacun (Utilisateurs → Inviter).",
      "Configurer au moins un transporteur de livraison (Livraison → Prestataires).",
      "Ajouter un ou plusieurs agents de confirmation si vous vendez en paiement à la livraison (Commissions → Ajouter un agent).",
    ],
    related: ["parametres/parametres-boutique", "integrations/connecter-woocommerce", "utilisateurs/invitation"],
    tryNow: { label: "Ouvrir les paramètres", href: "/parametres" },
    lastUpdated: LAST_UPDATED,
  },
  {
    slug: "bien-demarrer/checklist-de-demarrage",
    title: "Checklist de démarrage",
    category: "bien-demarrer",
    tagline: "Dans l'ordre, ce qu'il faut avoir fait avant de traiter des commandes réelles.",
    body: [
      {
        type: "list",
        items: [
          "☐ Informations de l'entreprise renseignées (Paramètres → Général)",
          "☐ Boutique WooCommerce/Shopify connectée et connexion testée avec succès",
          "☐ Entrepôt par défaut vérifié, produits importés avec leur stock",
          "☐ Coût d'achat renseigné sur les produits (sinon la rentabilité affichera « Coût manquant »)",
          "☐ Équipe invitée avec les bons rôles (Confirmation, Stock, Livraison, Comptable…)",
          "☐ Au moins un transporteur de livraison configuré",
          "☐ Correspondances de ville vérifiées pour ce transporteur",
          "☐ Agents de confirmation créés si vous utilisez le paiement à la livraison",
          "☐ Une commande de test créée, confirmée, expédiée et suivie de bout en bout",
        ],
      },
    ],
    related: ["bien-demarrer/configuration-initiale"],
    lastUpdated: LAST_UPDATED,
  },
  {
    slug: "bien-demarrer/comprendre-les-notifications",
    title: "Comprendre les notifications",
    category: "bien-demarrer",
    tagline: "Les alertes de stock, commandes, livraisons et intégrations qui vous concernent personnellement.",
    permission: "dashboard.view",
    prerequisites: [],
    steps: [
      "Ouvrir Notifications — chaque notification correspond à un événement (rupture de stock, échec de livraison, échec de synchronisation, retour client…).",
      "Une notification non lue est mise en évidence.",
      "Utiliser « Tout marquer comme lu » ou fermer une notification individuellement.",
    ],
    whatYouShouldSee: "Les 100 notifications les plus récentes qui vous sont adressées, les plus récentes en premier.",
    commonMistakes: ["Confondre les notifications (personnelles, dans la cloche) avec le Journal d'audit (historique complet de toute l'entreprise)."],
    related: ["utilisateurs/journal-audit"],
    tryNow: { label: "Ouvrir les notifications", href: "/notifications" },
    lastUpdated: LAST_UPDATED,
  },
  {
    slug: "bien-demarrer/assistant-ia",
    title: "Assistant IA",
    category: "bien-demarrer",
    tagline: "Des réponses rapides basées sur vos données réelles, à travers des questions prédéfinies adaptées à votre rôle.",
    permission: "ai.use",
    prerequisites: [],
    steps: [
      "Ouvrir Assistant IA.",
      "Choisir une question proposée dans la liste — la liste dépend de votre rôle : un rôle Stock verra des questions sur le stock, un rôle Finance des questions financières, etc.",
      "Lire la réponse, calculée à partir de vos données réelles.",
    ],
    body: [
      {
        type: "callout",
        tone: "info",
        text: "L'assistant ne répond qu'à des requêtes contrôlées sur vos données réelles — il n'invente jamais de chiffre. L'intégration d'un assistant conversationnel plus général est prévue pour une phase ultérieure.",
      },
    ],
    tryNow: { label: "Ouvrir l'Assistant IA", href: "/assistant-ia" },
    lastUpdated: LAST_UPDATED,
  },
];
