import type { DocArticle } from "../types";

const LAST_UPDATED = "2026-09-10";
/** Articles touched by the Inventory & Order Lifecycle v1 rewrite (physical returns). */
const STOCK_LIFECYCLE_UPDATE = "2026-09-15";

export const commandesArticles: DocArticle[] = [
  {
    slug: "commandes/creer-une-commande",
    title: "Créer une commande",
    category: "commandes",
    tagline: "Une commande peut être créée manuellement (téléphone, WhatsApp) ou arriver automatiquement depuis WooCommerce/Shopify.",
    permission: "orders.create",
    prerequisites: ["Le client existe déjà (ou est créé au même moment).", "Le ou les produits sont Actifs."],
    steps: [
      "Ouvrir Commandes → Nouvelle commande.",
      "Choisir le client.",
      "Ajouter un ou plusieurs articles (produit ou variation, quantité, remise éventuelle).",
      "Choisir le mode de paiement (dont Paiement à la livraison) et le canal (WhatsApp par défaut).",
      "Enregistrer — la commande est créée au statut Nouvelle.",
    ],
    whatYouShouldSee: "La commande apparaît dans Commandes au statut Nouvelle, et dans la file Confirmation si vous utilisez ce workflow.",
    body: [
      {
        type: "callout",
        tone: "info",
        text: "Le prix, le nom et le coût de chaque article sont toujours recalculés côté serveur à partir de la fiche produit — jamais à partir de ce qui a été saisi côté navigateur.",
      },
      { type: "p", text: "Le stock n'est pas réservé à la création — il ne l'est qu'au moment où la commande passe au statut Confirmée." },
    ],
    commonMistakes: ["Essayer d'ajouter un produit Brouillon ou Archivé à une commande — seuls les produits Actifs peuvent être vendus."],
    troubleshooting: [
      {
        symptom: "« Ce produit n'est plus disponible à la vente. »",
        cause: "Le produit (ou la variation) sélectionné n'a pas le statut Actif.",
        check: "Vérifiez le statut du produit dans Produits.",
        solution: "Réactivez le produit, ou choisissez un autre article.",
        expectedResult: "L'article peut être ajouté à la commande.",
        errorStrings: ["Ce produit n'est plus disponible à la vente."],
      },
      {
        symptom: "« Chaque article doit référencer un produit. »",
        cause: "Une ligne de la commande n'a ni produit ni variation sélectionné.",
        check: "Relisez chaque ligne d'article.",
        solution: "Sélectionnez un produit ou une variation pour chaque ligne.",
        expectedResult: "La commande peut être enregistrée.",
        errorStrings: ["Chaque article doit référencer un produit."],
      },
    ],
    related: ["commandes/comprendre-les-statuts", "commandes/commandes-provenant-de-woocommerce-shopify"],
    tryNow: { label: "Créer une commande", href: "/commandes/nouvelle" },
    lastUpdated: LAST_UPDATED,
  },
  {
    slug: "commandes/comprendre-les-statuts",
    title: "Comprendre les statuts",
    category: "commandes",
    tagline: "Une commande suit un cycle de vie strict — certaines transitions sont impossibles par conception.",
    permission: "orders.view",
    body: [
      {
        type: "table",
        headers: ["Statut", "Transitions possibles"],
        rows: [
          ["Nouvelle", "Confirmée, Annulée"],
          ["Confirmée", "En préparation, Annulée"],
          ["En préparation", "Expédiée, Annulée"],
          ["Expédiée", "Livrée, Échec, Retour"],
          ["Livrée", "Retour"],
          ["Échec", "En préparation, Annulée"],
          ["Retour", "Remboursée"],
          ["Annulée", "Nouvelle (uniquement via « Rétablir », si jamais expédiée)"],
          ["Remboursée", "— (statut final)"],
        ],
      },
      {
        type: "callout",
        tone: "info",
        text: "Le stock est réservé au passage à Confirmée, puis réellement déduit au passage à Expédiée. Passé ce point, aucune transition de statut — annulation, Échec, ni même le statut Retour — ne restitue automatiquement le stock : le stock physique n'est jamais restitué autrement que par une confirmation de retour physique explicite (voir « Confirmer un retour physique »).",
      },
    ],
    troubleshooting: [
      {
        symptom: "« Transition de statut invalide : X → Y. »",
        cause: "Le changement de statut demandé ne fait pas partie des transitions autorisées depuis le statut actuel (voir le tableau ci-dessus).",
        check: "Vérifiez le statut actuel de la commande et la transition tentée.",
        solution: "Passez par les statuts intermédiaires autorisés (ex. Confirmée → En préparation → Expédiée), plutôt que de sauter une étape.",
        expectedResult: "Le changement de statut réussit.",
        errorStrings: ["Transition de statut invalide"],
      },
    ],
    related: ["confirmation/statuts", "commandes/annuler", "commandes/confirmer-un-retour-physique"],
    tryNow: { label: "Ouvrir Commandes", href: "/commandes" },
    lastUpdated: STOCK_LIFECYCLE_UPDATE,
  },
  {
    slug: "commandes/confirmer-une-commande",
    title: "Confirmer une commande",
    category: "commandes",
    tagline: "Confirmer une commande valide la vente par téléphone avant expédition — voir le module Confirmation pour le détail du workflow.",
    permission: "orders.confirm",
    related: ["confirmation/workflow-de-confirmation", "confirmation/role-confirmation"],
    tryNow: { label: "Ouvrir la file de confirmation", href: "/confirmation" },
    lastUpdated: LAST_UPDATED,
  },
  {
    slug: "commandes/annuler",
    title: "Annuler une commande",
    category: "commandes",
    tagline: "Annuler une commande libère le stock qu'elle avait réservé. Une commande déjà expédiée ne récupère jamais son stock automatiquement.",
    permission: "orders.cancel",
    steps: ["Ouvrir la commande.", "Cliquer sur Annuler.", "Confirmer."],
    body: [
      {
        type: "callout",
        tone: "warning",
        text: "Annuler une commande déjà expédiée change uniquement son statut — le stock physique déjà déduit n'est ni recrédité ni marqué comme retourné automatiquement, même si les unités reviennent réellement en entrepôt. Utilisez « Confirmer un retour physique » sur la commande pour enregistrer ce qui est effectivement revenu.",
      },
    ],
    troubleshooting: [
      {
        symptom: "« Cette commande ne peut plus être annulée dans son statut actuel. »",
        cause: "La commande est déjà Livrée, Retour, Remboursée, ou déjà Annulée.",
        check: "Vérifiez le statut actuel de la commande.",
        solution: "Une commande Livrée qui doit être annulée passe plutôt par un retour (statut Retour) puis un remboursement.",
        expectedResult: "—",
        errorStrings: ["Cette commande ne peut plus être annulée dans son statut actuel."],
      },
      {
        symptom: "« Cette commande a été modifiée entre-temps par une autre action. Rechargez la page et réessayez. »",
        cause: "Une autre personne (ou une synchronisation automatique) a modifié cette commande au même moment.",
        check: "Rechargez la page pour voir l'état actuel de la commande.",
        solution: "Réessayez l'action après rechargement.",
        expectedResult: "L'action réussit sur l'état à jour de la commande.",
        errorStrings: ["Cette commande a été modifiée entre-temps par une autre action. Rechargez la page et réessayez."],
      },
    ],
    related: ["commandes/comprendre-les-statuts", "commandes/confirmer-un-retour-physique"],
    tryNow: { label: "Ouvrir Commandes", href: "/commandes" },
    lastUpdated: STOCK_LIFECYCLE_UPDATE,
  },
  {
    slug: "commandes/confirmer-un-retour-physique",
    title: "Confirmer un retour physique",
    category: "commandes",
    tagline: "La seule action qui recrédite réellement le stock après une expédition — enregistre ce qui est physiquement revenu, revendable ou endommagé.",
    permission: "orders.return",
    prerequisites: ["La commande a été expédiée (elle a une date d'expédition)."],
    steps: [
      "Ouvrir une commande déjà expédiée.",
      "Cliquer sur « Confirmer le retour physique ».",
      "Pour chaque article, saisir la quantité revendable reçue et/ou la quantité endommagée reçue.",
      "Ajouter une note optionnelle, puis confirmer.",
    ],
    whatYouShouldSee: "Le stock disponible augmente du nombre d'unités revendables. Les unités endommagées sont comptabilisées séparément et n'augmentent jamais le stock disponible. Un nouvel enregistrement apparaît dans « Retours physiques » sur la commande, avec l'auteur, l'heure et la note éventuelle.",
    body: [
      {
        type: "callout",
        tone: "info",
        text: "Totalement indépendant du statut de la commande — même une commande Annulée ou en Échec après expédition peut recevoir un retour physique, tant qu'elle a été expédiée. C'est la seule information qui compte : ce qui est physiquement revenu.",
      },
      {
        type: "list",
        items: [
          "Un retour peut se faire en plusieurs fois si les unités reviennent progressivement — le système retient toujours ce qui a déjà été déclaré.",
          "Impossible de déclarer plus d'unités revenues que ce qui a été expédié — c'est une limite stricte, jamais contournable.",
          "Enregistrer deux fois exactement la même confirmation (double clic, rechargement) ne crée jamais de doublon.",
        ],
      },
    ],
    troubleshooting: [
      {
        symptom: "Le bouton « Confirmer le retour physique » n'apparaît pas sur la commande",
        cause: "Soit la commande n'a jamais été expédiée, soit tout ce qui a été expédié a déjà été intégralement déclaré en retour (rien ne reste à retourner).",
        check: "Vérifiez la date d'expédition de la commande, et le contenu de la section « Retours physiques » si elle existe déjà.",
        solution: "Rien à faire si tout a déjà été retourné — sinon, la commande doit d'abord être expédiée.",
        expectedResult: "—",
      },
      {
        symptom: "« quantité saisie supérieure à la quantité restante »",
        cause: "La somme (revendable + endommagée) saisie pour un article dépasse ce qu'il reste à retourner pour cet article (quantité expédiée moins ce qui a déjà été déclaré).",
        check: "Regardez la colonne « Restante » affichée pour chaque article dans la fenêtre de retour.",
        solution: "Réduisez les quantités saisies pour que leur somme ne dépasse pas la quantité restante.",
        expectedResult: "Le retour se confirme normalement.",
        errorStrings: ["quantité saisie supérieure à la quantité restante"],
      },
    ],
    related: ["commandes/annuler", "commandes/comprendre-les-statuts", "stock/stock-disponible", "stock/mouvements"],
    tryNow: { label: "Ouvrir Commandes", href: "/commandes" },
    lastUpdated: STOCK_LIFECYCLE_UPDATE,
    keywords: ["retour physique", "produit endommagé", "RMA", "retour client", "marchandise retournée"],
  },
  {
    slug: "commandes/modifier-traiter-une-commande",
    title: "Modifier / traiter une commande",
    category: "commandes",
    tagline: "Depuis la fiche d'une commande : changer son statut, corriger l'adresse de livraison, enregistrer un remboursement.",
    permission: "orders.edit",
    steps: [
      "Ouvrir la commande.",
      "Utiliser le contrôle de statut pour l'avancer dans son cycle de vie.",
      "Modifier l'adresse de livraison si besoin (ceci ne change pas le carnet d'adresses du client, seulement cette commande).",
      "Pour un remboursement, utiliser Remboursements → Nouveau remboursement.",
    ],
    troubleshooting: [
      {
        symptom: "Le montant du remboursement dépasse ce qui reste remboursable",
        cause: "Le montant demandé dépasse le solde restant (total de la commande moins les remboursements déjà effectués ou en cours).",
        check: "Consultez le solde remboursable affiché sur la commande.",
        solution: "Réduisez le montant du remboursement au solde disponible.",
        expectedResult: "Le remboursement est enregistré.",
        errorStrings: ["Le montant dépasse le solde remboursable", "Cette commande a déjà été intégralement remboursée."],
      },
    ],
    related: ["clients/adresses", "finance/rentabilite"],
    tryNow: { label: "Ouvrir Commandes", href: "/commandes" },
    lastUpdated: LAST_UPDATED,
  },
  {
    slug: "commandes/commandes-provenant-de-woocommerce-shopify",
    title: "Commandes provenant de WooCommerce/Shopify",
    category: "commandes",
    tagline: "Les commandes importées suivent le même cycle de vie que les commandes manuelles, avec une synchronisation dans les deux sens sur certains statuts.",
    permission: "orders.view",
    body: [
      {
        type: "p",
        text: "Le paiement confirmé (Payé) et l'annulation sont renvoyés vers WooCommerce. La livraison confirmée renvoie le statut « Terminée » vers WooCommerce. Il n'existe pas d'action de « resynchronisation » pour une commande individuelle — seule la synchronisation groupée (Intégrations) réimporte les commandes.",
      },
    ],
    related: ["integrations/synchronisation-commandes"],
    tryNow: { label: "Ouvrir Commandes", href: "/commandes" },
    lastUpdated: LAST_UPDATED,
  },
  {
    slug: "commandes/problemes-frequents",
    title: "Problèmes fréquents",
    category: "commandes",
    tagline: "Les erreurs les plus courantes rencontrées sur les commandes.",
    permission: "orders.view",
    troubleshooting: [
      {
        symptom: "« Commande introuvable. »",
        cause: "L'identifiant de la commande dans le lien n'existe pas (souvent un lien copié depuis un autre compte, ou une commande supprimée).",
        check: "Revenez à la liste Commandes et rouvrez la commande depuis là.",
        solution: "Utilisez toujours la liste Commandes pour naviguer plutôt qu'un lien copié.",
        expectedResult: "La commande s'ouvre normalement.",
        errorStrings: ["Commande introuvable."],
      },
      {
        symptom: "« Le statut « Remboursé » ne peut être défini que via un remboursement complété. »",
        cause: "Vous essayez de forcer le statut de paiement à Remboursé directement, sans passer par un remboursement.",
        check: "—",
        solution: "Créez un remboursement et faites-le passer au statut Complété — le statut de paiement se met alors à jour automatiquement.",
        expectedResult: "Le statut de paiement passe à Remboursé.",
        errorStrings: ["Le statut « Remboursé » ne peut être défini que via un remboursement complété."],
      },
    ],
    related: ["commandes/comprendre-les-statuts", "commandes/annuler"],
    tryNow: { label: "Ouvrir Commandes", href: "/commandes" },
    lastUpdated: LAST_UPDATED,
  },
];
