import type { DocArticle } from "../types";

const LAST_UPDATED = "2026-09-10";

export const integrationsArticles: DocArticle[] = [
  {
    slug: "integrations/connecter-woocommerce",
    title: "Connecter WooCommerce",
    category: "integrations",
    tagline: "Relier votre boutique WooCommerce pour importer automatiquement produits et commandes.",
    permission: "integrations.manage",
    prerequisites: [
      "Une clé API WooCommerce avec permissions Lecture/Écriture (WooCommerce → Réglages → Avancé → API REST).",
      "L'URL de votre boutique (ex. https://maboutique.com).",
    ],
    steps: [
      "Ouvrir Intégrations.",
      "Choisir la carte WooCommerce et cliquer sur Connecter.",
      "Renseigner l'URL de la boutique, la Clé API et le Secret API.",
      "Enregistrer — la connexion est créée au statut « Configurée ».",
      "Cliquer sur « Tester la connexion » pour vérifier que les identifiants fonctionnent (voir « Tester une connexion »).",
    ],
    whatYouShouldSee: "Après un test réussi, le statut passe à « Connectée » et une première synchronisation peut démarrer.",
    commonMistakes: [
      "Enregistrer les identifiants sans tester la connexion — l'enregistrement seul ne vérifie rien, le statut reste « Configurée » jusqu'au test.",
      "Utiliser une clé API en lecture seule : la synchronisation du stock (poussée vers WooCommerce) a aussi besoin de l'écriture.",
    ],
    troubleshooting: [
      {
        symptom: "« L'URL de la boutique est requise. »",
        cause: "Le champ URL a été laissé vide.",
        check: "Vérifiez que le champ URL de la boutique est bien rempli avant d'enregistrer.",
        solution: "Renseignez l'URL complète de la boutique (ex. https://maboutique.com) puis enregistrez à nouveau.",
        expectedResult: "La connexion est enregistrée au statut « Configurée ».",
        errorStrings: ["L'URL de la boutique est requise."],
      },
      {
        symptom: "« La clé et le secret API sont requis pour WooCommerce. »",
        cause: "La clé API ou le secret API (ou les deux) sont vides.",
        check: "Régénérez une clé API dans WooCommerce → Réglages → Avancé → API REST si besoin.",
        solution: "Renseignez la Clé API et le Secret API, puis enregistrez.",
        expectedResult: "La connexion est enregistrée au statut « Configurée ».",
        errorStrings: ["La clé et le secret API sont requis pour WooCommerce."],
      },
    ],
    related: ["integrations/tester-une-connexion", "integrations/problemes-authentification"],
    tryNow: { label: "Ouvrir Intégrations", href: "/integrations" },
    lastUpdated: LAST_UPDATED,
  },
  {
    slug: "integrations/connecter-shopify",
    title: "Connecter Shopify",
    category: "integrations",
    tagline: "Relier votre boutique Shopify pour importer automatiquement produits et commandes.",
    permission: "integrations.manage",
    prerequisites: [
      "Un jeton d'accès Admin API Shopify (application personnalisée).",
      "Le nom de votre boutique Shopify (ex. mon-magasin ou mon-magasin.myshopify.com).",
    ],
    steps: [
      "Ouvrir Intégrations.",
      "Choisir la carte Shopify et cliquer sur Connecter.",
      "Renseigner le nom de la boutique et le Jeton d'accès Admin API (le Secret webhook est optionnel — utile seulement pour vérifier les webhooks).",
      "Enregistrer, puis tester la connexion.",
    ],
    body: [
      {
        type: "callout",
        tone: "warning",
        title: "Intégration Shopify",
        text: "Si votre déploiement affiche « L'intégration Shopify n'est pas encore disponible. », l'intégration est temporairement désactivée pour votre installation — contactez votre administrateur système.",
      },
    ],
    commonMistakes: ["Renseigner l'URL complète du panneau d'administration au lieu du simple nom de la boutique."],
    troubleshooting: [
      {
        symptom: "« Le nom de la boutique Shopify est requis. »",
        cause: "Le champ boutique a été laissé vide.",
        check: "Vérifiez le champ avant d'enregistrer.",
        solution: "Renseignez le nom de la boutique Shopify, puis enregistrez à nouveau.",
        expectedResult: "La connexion est enregistrée au statut « Configurée ».",
        errorStrings: ["Le nom de la boutique Shopify est requis."],
      },
      {
        symptom: "« Le jeton d'accès Admin API Shopify est requis. »",
        cause: "Le jeton d'accès n'a pas été renseigné.",
        check: "Générez un jeton d'accès Admin API depuis votre application personnalisée Shopify.",
        solution: "Renseignez le jeton, puis enregistrez.",
        expectedResult: "La connexion est enregistrée au statut « Configurée ».",
        errorStrings: ["Le jeton d'accès Admin API Shopify est requis."],
      },
      {
        symptom: "« L'intégration Shopify n'est pas encore disponible. »",
        cause: "L'intégration Shopify est désactivée par un interrupteur de déploiement (SHOPIFY_INTEGRATION_ENABLED).",
        check: "Cette limitation est au niveau du déploiement, pas de votre compte.",
        solution: "Contactez votre administrateur système pour activer l'intégration Shopify sur ce déploiement.",
        expectedResult: "Une fois activée, la connexion et la synchronisation Shopify fonctionnent normalement.",
        errorStrings: ["L'intégration Shopify n'est pas encore disponible."],
      },
    ],
    related: ["integrations/tester-une-connexion", "integrations/problemes-authentification"],
    tryNow: { label: "Ouvrir Intégrations", href: "/integrations" },
    lastUpdated: LAST_UPDATED,
  },
  {
    slug: "integrations/tester-une-connexion",
    title: "Tester une connexion",
    category: "integrations",
    tagline: "Vérifier que les identifiants saisis fonctionnent réellement — c'est la seule action qui fait passer une connexion au statut « Connectée ».",
    permission: "integrations.manage",
    prerequisites: ["Une connexion déjà enregistrée (voir Connecter WooCommerce / Connecter Shopify)."],
    steps: [
      "Ouvrir Intégrations.",
      "Sur la carte de la boutique concernée, cliquer sur « Tester la connexion ».",
    ],
    whatYouShouldSee: "Le statut passe à « Connectée ». En cas d'échec, il passe à « Erreur » et le message exact de la boutique est affiché.",
    troubleshooting: [
      {
        symptom: "Le test échoue avec un message d'authentification",
        cause: "Identifiants incorrects, révoqués, ou permissions insuffisantes sur la clé API.",
        check: "Consultez l'article « Problèmes d'authentification » — chaque message y est expliqué avec sa cause exacte.",
        solution: "Régénérez les identifiants dans WooCommerce/Shopify puis reconnectez.",
        expectedResult: "Le test passe et le statut devient « Connectée ».",
      },
    ],
    related: ["integrations/problemes-authentification", "integrations/synchronisation-produits"],
    tryNow: { label: "Ouvrir Intégrations", href: "/integrations" },
    lastUpdated: LAST_UPDATED,
  },
  {
    slug: "integrations/synchronisation-produits",
    title: "Synchronisation des produits",
    category: "integrations",
    tagline: "Les produits WooCommerce/Shopify sont importés automatiquement et peuvent être resynchronisés manuellement à tout moment.",
    permission: "integrations.manage",
    steps: [
      "Une fois la connexion « Connectée », les produits se synchronisent automatiquement via webhook à chaque création/modification côté boutique.",
      "Pour forcer une synchronisation complète, ouvrir Intégrations et cliquer sur « Synchroniser les produits » (ou le bouton « Synchroniser » combiné sur Produits/Commandes).",
      "Les variations d'un produit variable sont importées avec le produit parent — jamais comme des produits séparés.",
    ],
    body: [
      {
        type: "callout",
        tone: "info",
        text: "Un produit défini comme « produit externe » (WooCommerce/Shopify) ne peut pas être modifié (nom, prix, description) depuis ASODITECH — modifiez-le sur la plateforme d'origine. Seuls le coût d'achat, le suivi de stock et le seuil de stock faible restent modifiables depuis ASODITECH, car ce sont des réglages propres à ASODITECH.",
      },
      {
        type: "p",
        text: "Un produit supprimé sur WooCommerce ou Shopify n'est jamais supprimé dans ASODITECH — il est archivé automatiquement, pour garder son historique de ventes intact.",
      },
    ],
    commonMistakes: ["Essayer de modifier le nom ou le prix d'un produit importé directement depuis ASODITECH."],
    related: ["produits/produits-supprimes-woocommerce-shopify", "produits/comprendre-les-produits"],
    tryNow: { label: "Ouvrir Produits", href: "/produits" },
    lastUpdated: LAST_UPDATED,
    keywords: ["produit supprimé", "produit archivé automatiquement"],
  },
  {
    slug: "integrations/synchronisation-commandes",
    title: "Synchronisation des commandes",
    category: "integrations",
    tagline: "Les commandes WooCommerce/Shopify arrivent en temps réel par webhook, avec une synchronisation complète en secours.",
    permission: "integrations.manage",
    body: [
      {
        type: "p",
        text: "Deux mécanismes travaillent ensemble : les webhooks font arriver une commande en temps réel dès sa création côté boutique ; la synchronisation manuelle (bouton « Synchroniser ») est un filet de sécurité qui reprend automatiquement là où elle s'est arrêtée si un webhook a été manqué ou n'a jamais été configuré.",
      },
      {
        type: "p",
        text: "La synchronisation manuelle importe un nombre limité de commandes à chaque exécution et se relance elle-même tant qu'il en reste — inutile de la déclencher plusieurs fois d'affilée, laissez-la terminer.",
      },
    ],
    related: ["integrations/webhooks", "commandes/commandes-provenant-de-woocommerce-shopify"],
    tryNow: { label: "Ouvrir Intégrations", href: "/integrations" },
    lastUpdated: LAST_UPDATED,
  },
  {
    slug: "integrations/webhooks",
    title: "Webhooks",
    category: "integrations",
    tagline: "Les webhooks font arriver vos commandes et produits dans ASODITECH en temps réel, sans attendre une synchronisation manuelle.",
    permission: "integrations.manage",
    body: [
      {
        type: "p",
        text: "WooCommerce transmet la création/mise à jour de commande, la création/mise à jour/suppression de produit. Shopify transmet en plus l'annulation de commande, les remboursements et les mises à jour de niveau de stock.",
      },
      {
        type: "p",
        text: "Chaque webhook est vérifié par une signature secrète propre à votre connexion — pour WooCommerce, générez ce secret depuis Intégrations (« Générer un secret webhook ») ; pour Shopify, c'est le secret client de votre application personnalisée.",
      },
      {
        type: "callout",
        tone: "info",
        text: "Chaque webhook n'est appliqué qu'une seule fois, même reçu plusieurs fois — aucun risque de doublon en cas de re-livraison par la boutique.",
      },
    ],
    troubleshooting: [
      {
        symptom: "« Configurez d'abord la connexion WooCommerce. »",
        cause: "Vous essayez de générer un secret webhook avant d'avoir enregistré une connexion WooCommerce.",
        check: "Vérifiez qu'une connexion WooCommerce existe dans Intégrations.",
        solution: "Connectez d'abord WooCommerce, puis générez le secret webhook.",
        expectedResult: "Le secret webhook s'affiche une seule fois — copiez-le immédiatement dans WooCommerce.",
        errorStrings: ["Configurez d'abord la connexion WooCommerce."],
      },
    ],
    related: ["integrations/synchronisation-commandes", "integrations/problemes-synchronisation"],
    tryNow: { label: "Ouvrir Intégrations", href: "/integrations" },
    lastUpdated: LAST_UPDATED,
  },
  {
    slug: "integrations/problemes-authentification",
    title: "Problèmes d'authentification",
    category: "integrations",
    tagline: "Base de connaissances des messages d'erreur d'authentification WooCommerce/Shopify, avec leur cause exacte.",
    permission: "integrations.manage",
    troubleshooting: [
      {
        symptom: "Authentification WooCommerce refusée",
        cause: "La clé API ou le secret API sont incorrects, ont été régénérés côté WooCommerce, ou révoqués.",
        check: "Dans WooCommerce → Réglages → Avancé → API REST, vérifiez que la clé existe toujours et a les permissions Lecture/Écriture.",
        solution: "Régénérez une clé API avec les permissions Lecture/Écriture, puis reconnectez avec la nouvelle clé et le nouveau secret.",
        expectedResult: "Le test de connexion passe et le statut devient « Connectée ».",
        errorStrings: [
          "Authentification refusée par la boutique WooCommerce — vérifiez la clé et le secret API.",
          "Clé ou secret API refusés par la boutique WooCommerce. Régénérez une clé avec les permissions Lecture/Écriture dans WooCommerce → Réglages → Avancé → API REST, puis reconnectez.",
        ],
      },
      {
        symptom: "« La boutique n'a pas transmis Authorization »",
        cause:
          "Le serveur web de la boutique (fréquent avec LiteSpeed / Hostinger) bloque l'en-tête HTTP « Authorization » avant qu'il n'atteigne WooCommerce — les identifiants ne sont jamais reçus, même s'ils sont corrects.",
        check: "Confirmez l'hébergeur/serveur web de la boutique (LiteSpeed est le cas le plus fréquent).",
        solution: "Ajoutez la règle de réécriture qui transmet l'en-tête Authorization dans le fichier .htaccess de la boutique, puis testez à nouveau la connexion.",
        expectedResult: "L'en-tête est transmis, l'authentification réussit, le statut devient « Connectée ».",
        errorStrings: [
          "La boutique WooCommerce n'a pas reçu les identifiants API — le serveur web ne transmet pas l'en-tête « Authorization » à WooCommerce (fréquent avec LiteSpeed / Hostinger). Ajoutez la règle de réécriture correspondante dans le .htaccess de la boutique, puis réessayez.",
        ],
      },
      {
        symptom: "Accès refusé par la boutique (WooCommerce ou Shopify)",
        cause: "La clé/le jeton n'a pas les permissions nécessaires, ou l'utilisateur associé n'est pas administrateur de la boutique.",
        check: "Vérifiez le rôle de l'utilisateur WooCommerce associé à la clé, ou les « scopes » accordés au jeton Shopify.",
        solution: "Recréez la clé/le jeton avec un compte administrateur et les permissions Lecture/Écriture, puis reconnectez.",
        expectedResult: "Le test de connexion réussit.",
        errorStrings: [
          "Accès refusé par la boutique WooCommerce — vérifiez que la clé API dispose des permissions de lecture/écriture requises.",
          "Accès refusé par Shopify — vérifiez que le jeton d'accès dispose des permissions (scopes) requises.",
        ],
      },
      {
        symptom: "Authentification Shopify refusée",
        cause: "Le jeton d'accès Admin API est incorrect, expiré ou révoqué.",
        check: "Vérifiez le jeton dans votre application personnalisée Shopify.",
        solution: "Générez un nouveau jeton d'accès Admin API, puis reconnectez.",
        expectedResult: "Le test de connexion réussit.",
        errorStrings: ["Authentification refusée par Shopify — vérifiez le jeton d'accès Admin API."],
      },
    ],
    related: ["integrations/tester-une-connexion", "integrations/problemes-synchronisation"],
    tryNow: { label: "Ouvrir Intégrations", href: "/integrations" },
    lastUpdated: LAST_UPDATED,
    keywords: ["authentification refusée", "connexion woocommerce échoue", "401", "403"],
  },
  {
    slug: "integrations/problemes-synchronisation",
    title: "Problèmes de synchronisation",
    category: "integrations",
    tagline: "Pourquoi une synchronisation peut échouer, et ce qu'il se passe quand une boutique se déconnecte.",
    permission: "integrations.manage",
    troubleshooting: [
      {
        symptom: "Synchronisation échouée",
        cause: "La boutique a répondu avec une erreur (boutique introuvable, requêtes limitées, boutique momentanément indisponible) pendant l'import.",
        check: "Consultez le message d'erreur exact affiché sur la carte de la connexion — il indique la cause précise renvoyée par la boutique.",
        solution: "Pour une limitation de requêtes ou une indisponibilité temporaire, réessayez plus tard. Pour une URL/boutique introuvable, vérifiez l'adresse saisie.",
        expectedResult: "La synchronisation suivante reprend exactement où elle s'était arrêtée — aucune commande n'est perdue.",
        errorStrings: [
          "La boutique WooCommerce a limité le nombre de requêtes. Réessayez plus tard.",
          "La boutique WooCommerce est momentanément indisponible.",
          "Ressource introuvable sur la boutique WooCommerce — vérifiez l'URL de la boutique.",
          "Shopify a limité le nombre de requêtes. Réessayez dans un instant.",
          "Shopify est momentanément indisponible.",
          "Boutique introuvable à cette adresse — vérifiez le nom de domaine Shopify.",
        ],
      },
      {
        symptom: "Bannière « … déconnecté(e). Les … commandes/produits importés restent visibles… »",
        cause: "La connexion a été volontairement déconnectée (bouton Déconnecter) ou son statut est passé à Déconnectée.",
        check: "Ouvrez Intégrations pour voir le statut exact de la connexion.",
        solution: "Cliquez sur « Reconnecter » depuis la bannière, ou reconfigurez la connexion depuis Intégrations.",
        expectedResult: "Une fois reconnectée et le test réussi, la synchronisation reprend — les commandes/produits déjà importés ne sont jamais supprimés pendant la déconnexion.",
      },
    ],
    related: ["integrations/problemes-authentification", "integrations/webhooks"],
    tryNow: { label: "Ouvrir Intégrations", href: "/integrations" },
    lastUpdated: LAST_UPDATED,
    keywords: ["sync échoue", "boutique déconnectée"],
  },
];
