import type { DocArticle } from "../types";

const LAST_UPDATED = "2026-09-10";

export const rapportsArticles: DocArticle[] = [
  {
    slug: "rapports/ventes",
    title: "Ventes",
    category: "rapports",
    tagline: "Chiffre d'affaires, nombre de commandes, panier moyen, taux de confirmation/livraison/retour — avec comparaison à la période précédente.",
    permission: "analytics.view",
    body: [
      { type: "p", text: "C'est le seul des 6 rapports qui affiche directement l'évolution par rapport à la période précédente (variation en %)." },
    ],
    related: ["rapports/filtres-et-comparaison-de-periodes"],
    tryNow: { label: "Ouvrir le rapport Ventes", href: "/rapports/ventes" },
    lastUpdated: LAST_UPDATED,
  },
  {
    slug: "rapports/rentabilite-produit",
    title: "Rentabilité produit",
    category: "rapports",
    tagline: "Chiffre d'affaires, coût et marge, détaillés par produit et par catégorie.",
    permission: "analytics.view",
    related: ["finance/rentabilite", "finance/pourquoi-cout-manquant"],
    tryNow: { label: "Ouvrir le rapport Rentabilité", href: "/rapports/rentabilite" },
    lastUpdated: LAST_UPDATED,
  },
  {
    slug: "rapports/stock",
    title: "Stock (valorisation et rotation)",
    category: "rapports",
    tagline: "La valeur du stock (au coût et au prix de vente) par entrepôt, et les articles dormants.",
    permission: "analytics.view",
    body: [{ type: "p", text: "Ce rapport est une photo de l'état actuel du stock — il n'a pas de sélection de période comme les autres rapports." }],
    related: ["stock/stock-disponible"],
    tryNow: { label: "Ouvrir le rapport Stock", href: "/rapports/stock" },
    lastUpdated: LAST_UPDATED,
  },
  {
    slug: "rapports/livraison",
    title: "Performance livraison",
    category: "rapports",
    tagline: "Taux de livraison, d'échec et de retour, délai moyen par transporteur et par ville, et suivi du COD encaissé.",
    permission: "analytics.view",
    related: ["livraison/cod", "livraison/cycle-de-vie-dune-expedition"],
    tryNow: { label: "Ouvrir le rapport Livraison", href: "/rapports/livraison" },
    lastUpdated: LAST_UPDATED,
  },
  {
    slug: "rapports/clients",
    title: "Clients",
    category: "rapports",
    tagline: "Nouveaux clients vs. clients récurrents, taux de réachat, meilleurs clients, répartition par ville.",
    permission: "analytics.view",
    related: ["clients/clients-recurrents"],
    tryNow: { label: "Ouvrir le rapport Clients", href: "/rapports/clients" },
    lastUpdated: LAST_UPDATED,
  },
  {
    slug: "rapports/tresorerie",
    title: "Trésorerie",
    category: "rapports",
    tagline: "Encaissements (par mode de paiement) comparés aux dépenses (par catégorie) et au coût de livraison, pour obtenir la trésorerie nette.",
    permission: "analytics.view",
    related: ["finance/depenses", "livraison/cod"],
    tryNow: { label: "Ouvrir le rapport Trésorerie", href: "/rapports/tresorerie" },
    lastUpdated: LAST_UPDATED,
  },
  {
    slug: "rapports/analyses",
    title: "Analyses",
    category: "rapports",
    tagline: "Une vue rapide, sur le mois/trimestre/année en cours, de l'évolution du chiffre d'affaires, de la répartition des commandes par statut et par canal, et des meilleurs produits.",
    permission: "analytics.view",
    body: [
      {
        type: "p",
        text: "Analyses est un tableau de pilotage rapide, distinct des 6 rapports détaillés — il partage le même moteur de rentabilité (le même calcul de coût et de marge) que Finance et Rapports, donc les mêmes règles (coût manquant, exclusions de statuts) s'y appliquent.",
      },
    ],
    related: ["rapports/ventes", "finance/rentabilite"],
    tryNow: { label: "Ouvrir Analyses", href: "/analyses" },
    lastUpdated: LAST_UPDATED,
  },
  {
    slug: "rapports/filtres-et-comparaison-de-periodes",
    title: "Filtres, comparaison de périodes, CSV / PDF",
    category: "rapports",
    tagline: "Chaque rapport partage la même barre de filtres et les mêmes options d'export.",
    permission: "analytics.view",
    steps: [
      "Choisir la période (ou, pour le rapport Ventes, comparer à la période précédente).",
      "Cliquer sur « Exporter CSV » pour télécharger les données brutes.",
      "Cliquer sur le bouton d'impression pour obtenir une version PDF via l'impression du navigateur.",
    ],
    body: [
      { type: "p", text: "Une facture de livraison imprimable par expédition existe séparément, accessible depuis la page Rapports (« Factures de livraison »)." },
    ],
    related: ["rapports/ventes"],
    tryNow: { label: "Ouvrir Rapports", href: "/rapports" },
    lastUpdated: LAST_UPDATED,
  },
];
