import type { DocArticle } from "../types";

const LAST_UPDATED = "2026-09-10";

export const stockArticles: DocArticle[] = [
  {
    slug: "stock/entrepots",
    title: "Entrepôts",
    category: "stock",
    tagline: "Un entrepôt (ou point de vente) est un emplacement physique qui détient son propre stock.",
    permission: "inventory.view",
    steps: [
      "Ouvrir Emplacements → Nouvel entrepôt.",
      "Renseigner le nom et le type (Entrepôt par défaut).",
      "Enregistrer.",
    ],
    body: [
      { type: "p", text: "Un entrepôt géré par une intégration externe (ex. un « Location » Shopify) est en lecture seule dans ASODITECH — il ne peut être ni renommé ni désactivé depuis cette interface." },
    ],
    troubleshooting: [
      {
        symptom: "« Cet emplacement est géré par une intégration externe et ne peut pas être modifié ici. »",
        cause: "L'entrepôt provient de Shopify (Location) plutôt que d'avoir été créé dans ASODITECH.",
        check: "Vérifiez la source de l'entrepôt sur sa fiche.",
        solution: "Modifiez-le depuis Shopify — les modifications se synchroniseront.",
        expectedResult: "—",
        errorStrings: ["Cet emplacement est géré par une intégration externe et ne peut pas être modifié ici."],
      },
    ],
    related: ["stock/entrepot-par-defaut"],
    tryNow: { label: "Ouvrir Emplacements", href: "/entrepots" },
    lastUpdated: LAST_UPDATED,
  },
  {
    slug: "stock/entrepot-par-defaut",
    title: "Entrepôt par défaut",
    category: "stock",
    tagline: "L'entrepôt utilisé automatiquement pour toute commande qui ne précise pas d'entrepôt de préparation.",
    permission: "inventory.view",
    body: [
      {
        type: "p",
        text: "Chaque compte reçoit automatiquement un entrepôt par défaut (« Entrepôt principal ») à sa création. Il ne peut jamais être désactivé depuis l'interface — c'est une protection intentionnelle pour qu'il existe toujours un entrepôt de repli.",
      },
    ],
    troubleshooting: [
      {
        symptom: "« L'emplacement par défaut ne peut pas être désactivé. »",
        cause: "Vous essayez de désactiver l'entrepôt marqué par défaut.",
        check: "—",
        solution: "Si vous voulez changer d'entrepôt principal, contactez le support — ce changement n'est pas exposé dans l'interface actuelle.",
        expectedResult: "—",
        errorStrings: ["L'emplacement par défaut ne peut pas être désactivé."],
      },
      {
        symptom: "« Entrepôt de préparation invalide. » lors de la création d'une commande",
        cause: "Un entrepôt a été explicitement choisi pour la commande, mais il n'existe pas ou n'est pas actif.",
        check: "Vérifiez la liste des entrepôts actifs dans Emplacements.",
        solution: "Choisissez un entrepôt actif, ou laissez le champ vide pour utiliser l'entrepôt par défaut.",
        expectedResult: "La commande est créée.",
        errorStrings: ["Entrepôt de préparation invalide."],
      },
    ],
    related: ["stock/entrepots"],
    tryNow: { label: "Ouvrir Emplacements", href: "/entrepots" },
    lastUpdated: LAST_UPDATED,
    keywords: ["aucun entrepôt par défaut"],
  },
  {
    slug: "stock/stock-disponible",
    title: "Stock disponible",
    category: "stock",
    tagline: "Le stock disponible n'est jamais stocké tel quel — il se calcule toujours à partir du stock physique moins ce qui est réservé.",
    permission: "inventory.view",
    body: [
      {
        type: "code",
        lang: "text",
        code: "Stock disponible = max(0, Quantité en stock − Quantité réservée)",
      },
      {
        type: "list",
        items: [
          "Quantité en stock — la quantité physiquement présente.",
          "Quantité réservée — retenue pour des commandes confirmées mais pas encore expédiées.",
          "Quantité endommagée — suivie séparément, ne réduit pas la quantité en stock.",
        ],
      },
    ],
    related: ["stock/mouvements", "stock/produits-sans-stock"],
    tryNow: { label: "Ouvrir Stock", href: "/stock" },
    lastUpdated: LAST_UPDATED,
  },
  {
    slug: "stock/mouvements",
    title: "Mouvements",
    category: "stock",
    tagline: "Chaque changement de stock est enregistré dans un historique — jamais une simple modification silencieuse du chiffre.",
    permission: "inventory.view",
    body: [
      {
        type: "list",
        items: [
          "Réception, Vente, Retour, Endommagé",
          "Ajustement positif / négatif (correction manuelle)",
          "Réservation / Libération (au fil du cycle de vie d'une commande)",
          "Transfert sortant / Transfert entrant (entre deux entrepôts)",
          "Inventaire (correction issue d'un comptage physique)",
        ],
      },
    ],
    related: ["stock/corrections", "stock/transferts"],
    tryNow: { label: "Ouvrir Stock", href: "/stock" },
    lastUpdated: LAST_UPDATED,
  },
  {
    slug: "stock/transferts",
    title: "Transferts",
    category: "stock",
    tagline: "Déplacer du stock d'un entrepôt vers un autre, en deux étapes : expédition puis réception.",
    permission: "inventory.transfer",
    prerequisites: ["Un entrepôt source et un entrepôt destination, tous deux actifs."],
    steps: [
      "Ouvrir Transferts → Nouveau transfert.",
      "Choisir l'entrepôt source et l'entrepôt destination, ajouter les articles et quantités.",
      "Enregistrer comme brouillon (rien n'est encore déplacé).",
      "Expédier le transfert — le stock est immédiatement déduit de l'entrepôt source.",
      "À la réception physique, saisir la quantité réellement reçue par ligne (peut être inférieure à la quantité envoyée) et Recevoir — le stock est ajouté à l'entrepôt destination.",
    ],
    body: [
      {
        type: "callout",
        tone: "warning",
        text: "Une fois le transfert expédié, l'action ne peut plus être annulée. Une quantité manquante à la réception reste manquante — elle n'est pas restituée à l'entrepôt source.",
      },
    ],
    whatYouShouldSee: "Le transfert passe de Brouillon à En transit puis à Reçu.",
    troubleshooting: [
      {
        symptom: "« Stock introuvable à l'entrepôt source pour un article du transfert. »",
        cause: "L'entrepôt source n'a pas assez de stock disponible pour cet article au moment de l'expédition.",
        check: "Vérifiez le stock disponible de l'article dans l'entrepôt source.",
        solution: "Réduisez la quantité du transfert, ou approvisionnez d'abord l'entrepôt source.",
        expectedResult: "Le transfert peut être expédié.",
        errorStrings: ["Stock introuvable à l'entrepôt source pour un article du transfert."],
      },
      {
        symptom: "« L'entrepôt de destination est inactif — réactivez-le pour recevoir ce transfert. »",
        cause: "L'entrepôt destination a été désactivé entre l'expédition et la réception.",
        check: "Vérifiez le statut de l'entrepôt destination dans Emplacements.",
        solution: "Réactivez l'entrepôt destination, puis recevez le transfert.",
        expectedResult: "Le transfert peut être reçu.",
        errorStrings: ["L'entrepôt de destination est inactif — réactivez-le pour recevoir ce transfert."],
      },
      {
        symptom: "« Seul un transfert au statut « brouillon » peut être modifié / annulé. »",
        cause: "Le transfert a déjà été expédié ou reçu.",
        check: "Vérifiez le statut du transfert.",
        solution: "Un transfert déjà expédié ne peut plus être annulé — il doit être reçu (même partiellement) pour se clore normalement.",
        expectedResult: "—",
        errorStrings: ["Seul un transfert au statut « brouillon » peut être modifié.", "Seul un transfert au statut « brouillon » peut être annulé."],
      },
    ],
    related: ["stock/entrepots", "stock/mouvements"],
    tryNow: { label: "Ouvrir Transferts", href: "/transferts" },
    lastUpdated: LAST_UPDATED,
  },
  {
    slug: "stock/inventaire-stocktake",
    title: "Inventaire / stocktake",
    category: "stock",
    tagline: "Compter physiquement le stock d'un entrepôt et corriger automatiquement les écarts constatés.",
    permission: "inventory.count",
    prerequisites: ["Aucun autre inventaire déjà en cours pour cet entrepôt."],
    steps: [
      "Ouvrir Inventaires → Nouvel inventaire, choisir l'entrepôt.",
      "Un inventaire est créé avec une ligne pour chaque article détenu par cet entrepôt (y compris ceux à zéro).",
      "Saisir la quantité comptée pour chaque ligne au fur et à mesure du comptage physique.",
      "Clôturer l'inventaire une fois le comptage terminé.",
    ],
    body: [
      {
        type: "p",
        text: "À la clôture, chaque ligne comptée est comparée à la quantité système : l'écart (positif ou négatif) est appliqué comme un mouvement de stock « Inventaire ». Les lignes non comptées sont simplement ignorées, sans impact.",
      },
    ],
    whatYouShouldSee: "Un message de succès du type « Inventaire clôturé — N ajustement(s), N sans écart, N non compté(s). »",
    troubleshooting: [
      {
        symptom: "« Un inventaire est déjà en cours pour cet entrepôt. »",
        cause: "Un seul inventaire En cours est autorisé par entrepôt à la fois.",
        check: "Ouvrez Inventaires et retrouvez la session en cours pour cet entrepôt.",
        solution: "Clôturez ou annulez l'inventaire en cours avant d'en démarrer un nouveau.",
        expectedResult: "Un nouvel inventaire peut être créé.",
        errorStrings: ["Un inventaire est déjà en cours pour cet entrepôt."],
      },
      {
        symptom: "« N ligne(s) ont changé de stock depuis le comptage. Recomptez ces lignes puis clôturez à nouveau. »",
        cause: "Le stock d'un article compté a bougé (vente, réception…) entre le comptage et la clôture — la clôture est bloquée pour ne jamais appliquer un écart obsolète.",
        check: "Identifiez les lignes signalées.",
        solution: "Recomptez uniquement ces lignes, puis relancez la clôture.",
        expectedResult: "La clôture réussit, aucun mouvement incorrect n'est appliqué.",
        errorStrings: ["ligne(s) ont changé de stock depuis le comptage. Recomptez ces lignes puis clôturez à nouveau."],
      },
    ],
    related: ["stock/corrections", "stock/mouvements"],
    tryNow: { label: "Ouvrir Inventaires", href: "/inventaires" },
    lastUpdated: LAST_UPDATED,
  },
  {
    slug: "stock/corrections",
    title: "Corrections",
    category: "stock",
    tagline: "Un ajustement manuel modifie le stock d'un article dans un entrepôt, avec un motif enregistré.",
    permission: "inventory.adjust",
    steps: ["Ouvrir Stock, trouver l'article dans l'entrepôt concerné.", "Utiliser Ajuster le stock, saisir la quantité et le motif."],
    troubleshooting: [
      {
        symptom: "« Cet ajustement rendrait le stock négatif. »",
        cause: "L'ajustement négatif demandé dépasse la quantité en stock actuelle.",
        check: "Vérifiez la quantité en stock actuelle de l'article.",
        solution: "Réduisez la quantité de l'ajustement.",
        expectedResult: "L'ajustement est appliqué.",
        errorStrings: ["Cet ajustement rendrait le stock négatif."],
      },
      {
        symptom: "« Cet entrepôt est désactivé. Réactivez-le pour ajuster son stock. »",
        cause: "L'entrepôt visé n'est pas actif.",
        check: "Vérifiez le statut de l'entrepôt dans Emplacements.",
        solution: "Réactivez l'entrepôt avant d'ajuster son stock.",
        expectedResult: "L'ajustement est appliqué.",
        errorStrings: ["Cet entrepôt est désactivé. Réactivez-le pour ajuster son stock."],
      },
    ],
    related: ["stock/inventaire-stocktake"],
    tryNow: { label: "Ouvrir Stock", href: "/stock" },
    lastUpdated: LAST_UPDATED,
  },
  {
    slug: "stock/produits-sans-stock",
    title: "Produits sans stock",
    category: "stock",
    tagline: "Un article en rupture ou en stock faible est mis en évidence, et une notification est envoyée aux personnes concernées.",
    permission: "inventory.view",
    body: [
      {
        type: "list",
        items: [
          "Badge « Rupture » — le stock disponible est à 0 ou moins.",
          "Badge « Stock faible » — la quantité en stock est inférieure ou égale au seuil défini sur le produit (5 par défaut).",
        ],
      },
      { type: "p", text: "Une notification est envoyée (une seule fois par jour et par article) à toute personne ayant la permission de voir le stock." },
    ],
    related: ["produits/stock-produit", "stock/stock-disponible"],
    tryNow: { label: "Ouvrir Stock", href: "/stock" },
    lastUpdated: LAST_UPDATED,
  },
  {
    slug: "stock/problemes-frequents",
    title: "Problèmes fréquents",
    category: "stock",
    tagline: "Les blocages les plus courants côté stock, transferts et inventaires.",
    permission: "inventory.view",
    troubleshooting: [
      {
        symptom: "« Aucun enregistrement de stock trouvé pour ce produit dans cet entrepôt. »",
        cause: "Le produit n'a jamais eu de ligne de stock créée dans cet entrepôt précis (souvent un produit créé après l'entrepôt, ou un entrepôt secondaire jamais approvisionné).",
        check: "Vérifiez dans quel(s) entrepôt(s) le produit a déjà du stock.",
        solution: "Faites un transfert vers cet entrepôt, ou créez la ligne de stock via une réception.",
        expectedResult: "L'ajustement ou le transfert peut se faire normalement.",
        errorStrings: ["Aucun enregistrement de stock trouvé pour ce produit dans cet entrepôt."],
      },
      {
        symptom: "Le stock d'un produit synchronisé avec Shopify/WooCommerce ne correspond pas",
        cause: "Un délai de synchronisation, ou une variation dont le stock n'est pas celui attendu (chaque variation a son propre stock, indépendant du produit parent).",
        check: "Vérifiez le stock au niveau de la variation exacte, pas seulement du produit parent.",
        solution: "Relancez une synchronisation depuis Intégrations si le délai semble anormal.",
        expectedResult: "Le stock affiché correspond à la boutique d'origine.",
      },
    ],
    related: ["stock/stock-disponible", "integrations/synchronisation-produits"],
    tryNow: { label: "Ouvrir Stock", href: "/stock" },
    lastUpdated: LAST_UPDATED,
  },
];
