import "server-only";

import { verifyHmacSha256Base64 } from "@/lib/integrations/shared/hmac";

/**
 * Verifies a Shopify webhook delivery signature.
 *
 * Confirmed from Shopify's official webhook documentation during Phase
 * 21: the `X-Shopify-Hmac-SHA256` header is
 * base64(HMAC-SHA256(raw request body, the app's client secret)) — the
 * exact same algorithm WooCommerce uses (base64/HMAC-SHA256), just a
 * different header name and a different secret source. Unlike
 * WooCommerce (where this system generates the webhook secret and hands
 * it to WooCommerce), Shopify's signing secret is the custom app's own
 * "Client secret" / "API secret key", generated BY Shopify and retrieved
 * by the operator from their custom app's API credentials page — this
 * system never generates it. See docs/adr/0011-shopify-integration.md.
 */
export function verifyShopifyWebhookSignature(rawBody: string, signatureHeader: string | null, secret: string): boolean {
  return verifyHmacSha256Base64(rawBody, signatureHeader, secret);
}
